test list reviewers
Ivan6813/test-sprint-marathon pull request #29
Opened 2023-01-31 08:44 UTC by Ivan6813

2023-01-31 08:45 UTC, Ivan6813 commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675154714/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675154714/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675154714/book-page.png)

2023-01-31 08:48 UTC, klichkovskiy requested changes

2023-01-31 08:48 UTC, klichkovskiy commented on README.md
> +# test-sprint-marathon Здесь могла быть ваша реклама
Первый комент

2023-01-31 08:48 UTC, klichkovskiy commented on README.md
> +# test-sprint-marathon Здесь могла быть ваша реклама
Продам гараж

2023-01-31 08:58 UTC, SergeyGlazun requested changes
Строго нельзя ничего трогать в папках: .github,cypress, public и файле cypress.config.ts

2023-01-31 09:01 UTC, dariavorom requested changes

2023-01-31 09:01 UTC, dariavorom commented on README.md
> +# test-sprint-marathon Здесь могла быть ваша реклама
И ваша

2023-01-31 09:02 UTC, ValadzkoAliaksei requested changes

2023-01-31 09:02 UTC, ValadzkoAliaksei commented on README.md
> +# test-sprint-marathon Здесь могла быть ваша реклама
Куплю гараж

2023-01-31 09:04 UTC, Ivan6813 commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675155857/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675155857/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675155857/book-page.png)

2023-02-06 14:33 UTC, Ivan6813 commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675694014/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675694014/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675694014/book-page.png)

2023-02-06 14:35 UTC, Ivan6813 commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675694123/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675694123/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Ivan6813/1675694123/book-page.png)

2023-02-06 14:40 UTC, closed without merging