Update README.md
Ivan6813/test-sprint-marathon pull request #32
Opened 2023-02-24 07:27 UTC by Ivan6813

2023-02-24 07:33 UTC, klichkovskiy requested changes

2023-02-24 07:33 UTC, klichkovskiy commented on README.md
> +# Краткое описание спринта 132
переделать

2023-02-24 07:33 UTC, klichkovskiy commented on README.md
>  В данном спринте вам необходимо реализовать сортировку и фильтрацию книг, а так же добавить возможность возврата на главную страницу из хлебных крошек на странице книги.
переделать

2023-02-24 08:15 UTC, klichkovskiy approved these changes

2023-02-24 09:42 UTC, Gaurrus requested changes

2023-02-24 09:42 UTC, Gaurrus commented on README.md
>   Переносить файлы из предыдущего спринта больше не нужно. Для начала работы вам необходимо просто создать новую ветку, в которой вы будете вести разработку, от ветки main. После того как вы выполнили
test 1

2023-02-24 09:42 UTC, Gaurrus commented on README.md
>  В данном спринте вам необходимо реализовать сортировку и фильтрацию книг, а так же добавить возможность возврата на главную страницу из хлебных крошек на странице книги.
test2

2023-02-24 09:42 UTC, Gaurrus commented on README.md
>  В данном спринте вам необходимо реализовать сортировку и фильтрацию книг, а так же добавить возможность возврата на главную страницу из хлебных крошек на странице книги.
test 3

2023-03-16 07:36 UTC, ValadzkoAliaksei approved these changes

2024-01-23 06:42 UTC, closed without merging